// frontend/src/app/pages/books/book-add.component.ts
import { Component, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from "@angular/forms";
import { Router, RouterModule } from "@angular/router";
import { BookService } from "../../services/book.service";

@Component({
  selector: "app-book-add",
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  template: `
    <div class="max-w-2xl mx-auto px-4 py-8">
      <div class="mb-8">
        <a routerLink="/books" class="text-blue-600 hover:text-blue-700">← Retour aux livres</a>
        <h1 class="text-4xl font-bold mt-4">Ajouter un nouveau livre</h1>
      </div>

      <div class="bg-white rounded-lg shadow-md p-8">
        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-6">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Titre *</label>
              <input type="text" formControlName="title" placeholder="Titre du livre" class="input-field" />
              <p *ngIf="form.get('title')?.hasError('required')" class="error-message">Le titre est requis</p>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Auteur *</label>
              <input type="text" formControlName="author" placeholder="Nom de l'auteur" class="input-field" />
              <p *ngIf="form.get('author')?.hasError('required')" class="error-message">L'auteur est requis</p>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">ISBN *</label>
              <input type="text" formControlName="isbn" placeholder="ex: 978-3-16-148410-0" class="input-field" />
              <p *ngIf="form.get('isbn')?.hasError('required')" class="error-message">L'ISBN est requis</p>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Genre *</label>
              <select formControlName="genres" class="input-field">
                <option value="">Sélectionner un genre</option>
                <option value="Fiction">Fiction</option>
                <option value="Non-Fiction">Non-Fiction</option>
                <option value="Science Fiction">Science Fiction</option>
                <option value="Fantasy">Fantasy</option>
                <option value="Mystery">Mystery</option>
                <option value="Thriller">Thriller</option>
                <option value="Romance">Romance</option>
                <option value="Biography">Biography</option>
                <option value="History">History</option>
                <option value="Self-Help">Self-Help</option>
                <option value="Poetry">Poetry</option>
                <option value="Drama">Drama</option>
                <option value="Horror">Horror</option>
                <option value="Adventure">Adventure</option>
                <option value="Children">Children</option>
                <option value="Young Adult">Young Adult</option>
                <option value="Classic">Classic</option>
                <option value="Philosophy">Philosophy</option>
                <option value="Religion">Religion</option>
                <option value="Science">Science</option>
                <option value="Technology">Technology</option>
                <option value="Art">Art</option>
                <option value="Music">Music</option>
                <option value="Travel">Travel</option>
                <option value="Cooking">Cooking</option>
                <option value="Sports">Sports</option>
                <option value="Business">Business</option>
                <option value="Economics">Economics</option>
              </select>
              <p *ngIf="form.get('genres')?.hasError('required')" class="error-message">Le genre est requis</p>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Langue *</label>
             <select formControlName="language" class="input-field">
  <option value="">Sélectionner une langue</option>
  <option value="English">English</option>
  <option value="French">Français</option>
  <option value="mg">Malagasy</option>
  <option value="Spanish">Español</option>
  <option value="German">Deutsch</option>
  <option value="Italian">Italian</option>
  <option value="Portuguese">Português</option>
  <option value="Arabic">العربية</option>
  <option value="Chinese">中文</option>
  <option value="Japanese">日本語</option>
  <option value="Russian">Русский</option>
  <option value="Hindi">हिन्दी</option>
  <option value="Swahili">Kiswahili</option>
  <option value="Dutch">Nederlands</option>
  <option value="Korean">한국어</option>
</select>
              <p *ngIf="form.get('language')?.hasError('required')" class="error-message">La langue est requise</p>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Nombre total de copies *</label>
              <input type="number" formControlName="totalCopies" placeholder="10" class="input-field" />
              <p *ngIf="form.get('totalCopies')?.hasError('required')" class="error-message">Le nombre de copies est requis</p>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Date de publication</label>
              <input type="date" formControlName="publishedDate" class="input-field" />
            </div>

          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Description *</label>
            <textarea formControlName="description" placeholder="Décrivez le livre..." rows="6" class="input-field"></textarea>
            <p *ngIf="form.get('description')?.hasError('required')" class="error-message">La description est requise</p>
          </div>

          <div *ngIf="error" class="p-4 bg-red-50 border border-red-200 rounded-lg">
            <p class="text-red-600">{{ error }}</p>
          </div>

          <div class="flex gap-4">
            <button type="submit" [disabled]="loading || form.invalid" class="btn-primary flex-1">
              {{ loading ? "Ajout en cours..." : "Ajouter le livre" }}
            </button>
            <a routerLink="/books" class="btn-secondary flex-1 text-center block">Annuler</a>
          </div>

        </form>
      </div>
    </div>
  `,
  styles: [],
})
export class BookAddComponent implements OnInit {
  form: FormGroup;
  loading = false;
  error = "";

  constructor(
    private fb: FormBuilder,
    private bookService: BookService,
    private router: Router,
  ) {
    this.form = this.fb.group({
      title: ["", Validators.required],
      author: ["", Validators.required],
      isbn: ["", Validators.required],
      genres: ["", Validators.required],
      language: ["", Validators.required],
      totalCopies: [1, [Validators.required, Validators.min(1)]],
      publishedDate: [""],
      description: ["", Validators.required],
    });
  }

  ngOnInit(): void {}

  onSubmit(): void {
    if (this.form.invalid) return;

    this.loading = true;
    this.error = "";

    const formData = { ...this.form.value };

    // Convert genres single value to array
    if (formData.genres) {
      formData.genres = [formData.genres];
    }

    // Convert publishedDate to publishedYear
    if (formData.publishedDate) {
      formData.publishedYear = new Date(formData.publishedDate).getFullYear();
    }
    delete formData.publishedDate;

    // Set availableCopies = totalCopies
    formData.availableCopies = formData.totalCopies;

    // Esory ny language — tsy alefa any amin'ny backend
    delete formData.language;

    this.bookService.createBook(formData).subscribe({
      next: (response) => {
        if (response.success) {
          const bookId = response.data?._id || response.book?._id;
          if (bookId) {
            this.router.navigate(["/books", bookId]);
          } else {
            this.router.navigate(["/books"]);
          }
        } else {
          this.error = response.error || "Erreur lors de l'ajout du livre";
        }
        this.loading = false;
      },
      error: (error) => {
        this.error = error.error?.error || "Erreur lors de l'ajout du livre";
        this.loading = false;
      },
    });
  }
}

// frontend/src/pages/Books/BookAdd.jsx
import React, { useState } from "react";
import { useNavigate, Link } from "react-router-dom";

const GENRES = [
  "Fiction",
  "Non-Fiction",
  "Science Fiction",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Romance",
  "Biography",
  "History",
  "Self-Help",
  "Poetry",
  "Drama",
  "Horror",
  "Adventure",
  "Children",
  "Young Adult",
  "Classic",
  "Philosophy",
  "Religion",
  "Science",
  "Technology",
  "Art",
  "Music",
  "Travel",
  "Cooking",
  "Sports",
  "Business",
  "Economics",
];

const LANGUAGES = [
  "English",
  "Français",
  "Español",
  "Deutsch",
  "Arabic",
  "Malagasy",
  "Autre",
];

const AddBook = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const [formData, setFormData] = useState({
    title: "",
    author: "",
    isbn: "",
    description: "",
    genres: [],
    language: "English",
    publisher: "",
    publishedYear: "",
    pages: "",
    totalCopies: 1,
    location: { shelf: "", row: "", section: "" },
    tags: "",
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleLocationChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      location: { ...prev.location, [name]: value },
    }));
  };

  const handleGenreToggle = (genre) => {
    setFormData((prev) => ({
      ...prev,
      genres: prev.genres.includes(genre)
        ? prev.genres.filter((g) => g !== genre)
        : [...prev.genres, genre],
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");
    setSuccess("");

    if (!formData.title || !formData.author || !formData.isbn) {
      setError("Titre, auteur et ISBN sont obligatoires");
      return;
    }

    setLoading(true);

    try {
      const token = localStorage.getItem("token");

      const payload = {
        title: formData.title,
        author: formData.author,
        isbn: formData.isbn,
        description: formData.description || undefined,
        genres: formData.genres,
        language: formData.language,
        publisher: formData.publisher || undefined,
        publishedYear: formData.publishedYear
          ? parseInt(formData.publishedYear)
          : undefined,
        pages: formData.pages ? parseInt(formData.pages) : undefined,
        totalCopies: parseInt(formData.totalCopies),
        location: {
          shelf: formData.location.shelf || undefined,
          row: formData.location.row || undefined,
          section: formData.location.section || undefined,
        },
        tags: formData.tags
          ? formData.tags
              .split(",")
              .map((t) => t.trim())
              .filter(Boolean)
          : [],
      };

      const response = await fetch("http://localhost:5000/api/books", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(payload),
      });

      const data = await response.json();

      if (!response.ok) {
        if (data.errors && Array.isArray(data.errors)) {
          throw new Error(data.errors.map((e) => e.message).join(", "));
        }
        throw new Error(data.error || "Erreur lors de l'ajout du livre");
      }

      setSuccess("Livre ajouté avec succès !");
      setTimeout(() => navigate("/books"), 1500);
    } catch (err) {
      setError(err.message || "Erreur de connexion au serveur");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <div className="bg-white rounded-lg shadow-md p-8 max-w-3xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold">📖 Ajouter un nouveau livre</h1>
          <Link
            to="/dashboard"
            className="text-gray-500 hover:text-gray-700 text-sm"
          >
            ← Retour
          </Link>
        </div>

        {error && (
          <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-red-600 text-sm">{error}</p>
          </div>
        )}
        {success && (
          <div className="mb-6 p-4 bg-green-50 border border-green-200 rounded-lg">
            <p className="text-green-600 text-sm">✅ {success}</p>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Titre */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Titre <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="title"
              value={formData.title}
              onChange={handleChange}
              maxLength={200}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Titre du livre"
              required
            />
          </div>

          {/* Auteur + ISBN */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Auteur <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                name="author"
                value={formData.author}
                onChange={handleChange}
                maxLength={100}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Nom de l'auteur"
                required
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                ISBN <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                name="isbn"
                value={formData.isbn}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="978-2-07-036024-5"
                required
              />
              <p className="text-xs text-gray-400 mt-1">
                Format : 978-x-xx-xxxxxx-x
              </p>
            </div>
          </div>

          {/* Éditeur + Année + Pages */}
          <div className="grid grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Éditeur
              </label>
              <input
                type="text"
                name="publisher"
                value={formData.publisher}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Gallimard"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Année
              </label>
              <input
                type="number"
                name="publishedYear"
                value={formData.publishedYear}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="2024"
                min="1000"
                max={new Date().getFullYear()}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Pages
              </label>
              <input
                type="number"
                name="pages"
                value={formData.pages}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="320"
                min="1"
              />
            </div>
          </div>

          {/* Langue + Exemplaires */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Langue
              </label>
              <select
                name="language"
                value={formData.language}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                {LANGUAGES.map((l) => (
                  <option key={l}>{l}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Nombre d'exemplaires <span className="text-red-500">*</span>
              </label>
              <input
                type="number"
                name="totalCopies"
                value={formData.totalCopies}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                min="0"
                required
              />
            </div>
          </div>

          {/* Localisation */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              📍 Localisation en bibliothèque
            </label>
            <div className="grid grid-cols-3 gap-4">
              <div>
                <input
                  type="text"
                  name="shelf"
                  value={formData.location.shelf}
                  onChange={handleLocationChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Étagère (ex: A)"
                />
              </div>
              <div>
                <input
                  type="text"
                  name="row"
                  value={formData.location.row}
                  onChange={handleLocationChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Rangée (ex: 3)"
                />
              </div>
              <div>
                <input
                  type="text"
                  name="section"
                  value={formData.location.section}
                  onChange={handleLocationChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Section (ex: SF)"
                />
              </div>
            </div>
          </div>

          {/* Description */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Description
            </label>
            <textarea
              name="description"
              value={formData.description}
              onChange={handleChange}
              rows={4}
              maxLength={2000}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Résumé du livre..."
            />
            <p className="text-xs text-gray-400 mt-1">
              {formData.description.length}/2000
            </p>
          </div>

          {/* Tags */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Tags{" "}
              <span className="text-xs text-gray-400">
                (séparés par des virgules)
              </span>
            </label>
            <input
              type="text"
              name="tags"
              value={formData.tags}
              onChange={handleChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="classique, aventure, jeunesse"
            />
          </div>

          {/* Genres */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Genres
            </label>
            <div className="flex flex-wrap gap-2">
              {GENRES.map((genre) => (
                <button
                  key={genre}
                  type="button"
                  onClick={() => handleGenreToggle(genre)}
                  className={`px-3 py-1 rounded-full text-sm border transition ${
                    formData.genres.includes(genre)
                      ? "bg-blue-600 text-white border-blue-600"
                      : "bg-white text-gray-600 border-gray-300 hover:border-blue-400"
                  }`}
                >
                  {genre}
                </button>
              ))}
            </div>
          </div>

          {/* Boutons */}
          <div className="flex gap-4 pt-4">
            <button
              type="submit"
              disabled={loading}
              className="flex-1 bg-blue-600 text-white py-3 rounded-lg font-semibold hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? "Ajout en cours..." : "📖 Ajouter le livre"}
            </button>
            <Link
              to="/dashboard"
              className="flex-1 text-center bg-gray-100 text-gray-700 py-3 rounded-lg font-semibold hover:bg-gray-200"
            >
              Annuler
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AddBook;
