// frontend/src/app/pages/books/book-list.component.ts
import { Component, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormBuilder, FormGroup, ReactiveFormsModule } from "@angular/forms";
import { RouterModule } from "@angular/router";
import { BookService } from "../../services/book.service";

@Component({
  selector: "app-book-list",
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  template: `
    <div class="max-w-7xl mx-auto px-4 py-8">
      <h1 class="text-4xl font-bold mb-8">Découvrez nos livres</h1>

      <!-- Filters -->
      <div class="bg-white rounded-lg shadow-md p-6 mb-8">
        <form
          [formGroup]="filterForm"
          class="grid grid-cols-1 md:grid-cols-3 gap-4"
        >
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2"
              >Rechercher</label
            >
            <input
              type="text"
              formControlName="search"
              placeholder="Titre, auteur..."
              class="w-full px-4 py-2 border border-gray-300 rounded-lg"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2"
              >Genre</label
            >
            <select
              formControlName="genre"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg"
            >
              <option value="">Tous les genres</option>
              <option value="Fiction">Fiction</option>
              <option value="Non-fiction">Non-fiction</option>
              <option value="Science">Science</option>
              <option value="Histoire">Histoire</option>
            </select>
          </div>
          <div class="flex items-end gap-2">
            <button (click)="applyFilters()" class="btn-primary flex-1">
              Rechercher
            </button>
            <button
              (click)="resetFilters()"
              type="button"
              class="btn-secondary"
            >
              Réinitialiser
            </button>
          </div>
        </form>
      </div>

      <!-- Loading -->
      <div *ngIf="loading" class="text-center py-12">
        <p class="text-gray-600">Chargement des livres...</p>
      </div>

      <!-- Books Grid -->
      <div
        *ngIf="!loading && books.length > 0"
        class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
      >
        <div
          *ngFor="let book of books"
          class="card overflow-hidden hover:shadow-xl transition"
        >
          <div
            class="aspect-video bg-gradient-to-br from-blue-100 to-blue-200 flex items-center justify-center"
          >
            <span class="text-4xl">📖</span>
          </div>
          <div class="p-4">
            <h3 class="font-bold text-lg mb-2 truncate">{{ book.title }}</h3>
            <p class="text-gray-600 text-sm mb-2">{{ book.author }}</p>
            <div class="flex justify-between items-center mb-4">
              <span
                *ngIf="book.genres && book.genres[0]"
                class="text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded"
                >{{ book.genres[0] }}</span
              >
              <span class="text-sm font-medium"
                >{{ book.availableCopies }}/{{ book.totalCopies }}</span
              >
            </div>
            <a
              [routerLink]="['/books', book._id]"
              class="btn-primary w-full text-center block"
            >
              Voir détails
            </a>
          </div>
        </div>
      </div>

      <!-- No results -->
      <div *ngIf="!loading && books.length === 0" class="text-center py-12">
        <p class="text-gray-600">Aucun livre trouvé</p>
      </div>

      <!-- Pagination -->
      <div
        *ngIf="!loading && books.length > 0"
        class="flex justify-center items-center gap-4 mt-8"
      >
        <button
          (click)="previousPage()"
          [disabled]="currentPage === 1"
          class="px-4 py-2 border border-gray-300 rounded-lg disabled:opacity-50"
        >
          Précédent
        </button>
        <span class="text-gray-600"
          >Page {{ currentPage }} / {{ totalPages }}</span
        >
        <button
          (click)="nextPage()"
          [disabled]="currentPage >= totalPages"
          class="px-4 py-2 border border-gray-300 rounded-lg disabled:opacity-50"
        >
          Suivant
        </button>
      </div>
    </div>
  `,
  styles: [],
})
export class BookListComponent implements OnInit {
  books: any[] = [];
  loading = false;
  filterForm: FormGroup;
  currentPage = 1;
  totalPages = 1;

  constructor(
    private bookService: BookService,
    private fb: FormBuilder,
  ) {
    this.filterForm = this.fb.group({
      search: [""],
      genre: [""],
    });
  }

  ngOnInit(): void {
    this.loadBooks();
  }

  loadBooks(): void {
    this.loading = true;
    const params = {
      page: this.currentPage,
      limit: 12,
      search: this.filterForm.value.search,
      genre: this.filterForm.value.genre,
    };

    this.bookService.getBooks(params).subscribe({
      next: (response) => {
        this.books = response.data;
        this.currentPage = response.pagination.currentPage;
        this.totalPages = response.pagination.totalPages;
        this.loading = false;
      },
      error: (error) => {
        console.error("Erreur lors du chargement des livres", error);
        this.loading = false;
      },
    });
  }

  applyFilters(): void {
    this.currentPage = 1;
    this.loadBooks();
  }

  resetFilters(): void {
    this.filterForm.reset();
    this.currentPage = 1;
    this.loadBooks();
  }

  nextPage(): void {
    if (this.currentPage < this.totalPages) {
      this.currentPage++;
      this.loadBooks();
    }
  }

  previousPage(): void {
    if (this.currentPage > 1) {
      this.currentPage--;
      this.loadBooks();
    }
  }
}

// frontend/src/pages/Books/BookList.jsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';

const BookList = () => {
  const [books, setBooks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedGenre, setSelectedGenre] = useState('');
  const [author, setAuthor] = useState('');
  const [minRating, setMinRating] = useState('');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalBooks, setTotalBooks] = useState(0);
  const [showFilters, setShowFilters] = useState(false);
  
  const { user } = useAuth();
  
  const genres = ['Fiction', 'Science Fiction', 'Fantasy', 'Classic', 'Aventure', 'Dystopie', 'Philosophie', 'Jeunesse', 'Historique', 'Romance'];

  useEffect(() => {
    loadBooks();
  }, [page, selectedGenre, minRating, author, searchTerm]);

  const loadBooks = async () => {
    setLoading(true);
    try {
      let url = `http://localhost:5000/api/books?page=${page}&limit=12`;
      if (searchTerm) url += `&search=${encodeURIComponent(searchTerm)}`;
      if (selectedGenre) url += `&genre=${encodeURIComponent(selectedGenre)}`;
      if (author) url += `&author=${encodeURIComponent(author)}`;
      if (minRating) url += `&minRating=${minRating}`;

      const res = await fetch(url);
      const data = await res.json();
      
      setBooks(data.data || []);
      setTotalPages(data.pagination?.totalPages || 1);
      setTotalBooks(data.pagination?.totalItems || 0);
    } catch (err) {
      console.error('Erreur:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = (e) => {
    e.preventDefault();
    setPage(1);
    loadBooks();
  };

  const resetFilters = () => {
    setSearchTerm('');
    setSelectedGenre('');
    setAuthor('');
    setMinRating('');
    setPage(1);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header avec stats */}
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">📚 Catalogue</h1>
            <p className="text-gray-600 mt-1">{totalBooks} livres disponibles</p>
          </div>
          <button
            onClick={() => setShowFilters(!showFilters)}
            className="btn-secondary flex items-center space-x-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z" />
            </svg>
            <span>Filtres</span>
          </button>
        </div>

        {/* Barre de recherche principale */}
        <form onSubmit={handleSearch} className="mb-6">
          <div className="relative">
            <input
              type="text"
              placeholder="Rechercher un livre par titre, auteur ou ISBN..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="input-field pl-12 pr-24 py-4 text-lg"
            />
            <svg className="absolute left-4 top-4 w-6 h-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
            <button
              type="submit"
              className="absolute right-2 top-2 btn-primary"
            >
              Rechercher
            </button>
          </div>
        </form>

        {/* Filtres avancés */}
        {showFilters && (
          <div className="bg-white rounded-xl shadow-sm p-6 mb-8 animate-fadeIn">
            <h3 className="font-semibold text-gray-900 mb-4">Filtres avancés</h3>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <select
                value={selectedGenre}
                onChange={(e) => setSelectedGenre(e.target.value)}
                className="input-field"
              >
                <option value="">Tous les genres</option>
                {genres.map(g => <option key={g} value={g}>{g}</option>)}
              </select>

              <input
                type="text"
                placeholder="Auteur"
                value={author}
                onChange={(e) => setAuthor(e.target.value)}
                className="input-field"
              />

              <select
                value={minRating}
                onChange={(e) => setMinRating(e.target.value)}
                className="input-field"
              >
                <option value="">Toutes les notes</option>
                <option value="4">4+ étoiles</option>
                <option value="3">3+ étoiles</option>
                <option value="2">2+ étoiles</option>
              </select>

              <button
                onClick={resetFilters}
                className="btn-secondary"
              >
                Réinitialiser
              </button>
            </div>
          </div>
        )}

        {/* Résultats */}
        {loading ? (
          <div className="flex justify-center items-center py-20">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
          </div>
        ) : books.length === 0 ? (
          <div className="text-center py-20 bg-white rounded-xl">
            <span className="text-6xl mb-4 block">🔍</span>
            <h3 className="text-xl font-semibold text-gray-900 mb-2">Aucun livre trouvé</h3>
            <p className="text-gray-600">Essayez de modifier vos critères de recherche</p>
          </div>
        ) : (
          <>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {books.map(book => (
                <Link to={`/books/${book._id}`} key={book._id}>
                  <div className="card group cursor-pointer h-full">
                    <div className="relative overflow-hidden rounded-t-xl">
                      <div className="aspect-[3/4] bg-gradient-to-br from-primary-100 to-primary-200 flex items-center justify-center">
                        <span className="text-7xl transform group-hover:scale-110 transition duration-300">📖</span>
                      </div>
                      <div className={`absolute top-3 right-3 px-3 py-1 rounded-full text-xs font-semibold
                        ${book.availableCopies > 0 
                          ? 'bg-green-100 text-green-700' 
                          : 'bg-red-100 text-red-700'}`}>
                        {book.availableCopies > 0 ? 'Disponible' : 'Indisponible'}
                      </div>
                    </div>
                    
                    <div className="p-5">
                      <h3 className="font-bold text-lg text-gray-900 mb-1 line-clamp-1">{book.title}</h3>
                      <p className="text-gray-600 text-sm mb-3">{book.author}</p>
                      
                      <div className="flex items-center mb-3">
                        <div className="flex items-center">
                          {[...Array(5)].map((_, i) => (
                            <svg key={i} className={`w-4 h-4 ${i < Math.floor(book.averageRating || 0) ? 'text-yellow-400' : 'text-gray-300'}`} fill="currentColor" viewBox="0 0 20 20">
                              <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                            </svg>
                          ))}
                        </div>
                        <span className="text-xs text-gray-500 ml-2">({book.totalReviews || 0})</span>
                      </div>
                      
                      <div className="flex items-center justify-between">
                        <span className="text-sm text-gray-500">
                          {book.availableCopies}/{book.totalCopies} dispo
                        </span>
                        <span className="text-primary-600 group-hover:translate-x-2 transition-transform">
                          →
                        </span>
                      </div>
                    </div>
                  </div>
                </Link>
              ))}
            </div>

            {/* Pagination */}
            {totalPages > 1 && (
              <div className="flex justify-center items-center space-x-2 mt-8">
                <button
                  onClick={() => setPage(p => Math.max(1, p-1))}
                  disabled={page === 1}
                  className="p-2 rounded-lg border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  ←
                </button>
                
                {[...Array(Math.min(5, totalPages))].map((_, i) => {
                  let pageNum;
                  if (totalPages <= 5) {
                    pageNum = i + 1;
                  } else if (page <= 3) {
                    pageNum = i + 1;
                  } else if (page >= totalPages - 2) {
                    pageNum = totalPages - 4 + i;
                  } else {
                    pageNum = page - 2 + i;
                  }
                  
                  return (
                    <button
                      key={i}
                      onClick={() => setPage(pageNum)}
                      className={`w-10 h-10 rounded-lg ${
                        page === pageNum
                          ? 'bg-primary-600 text-white'
                          : 'border border-gray-300 hover:bg-gray-50'
                      }`}
                    >
                      {pageNum}
                    </button>
                  );
                })}
                
                <button
                  onClick={() => setPage(p => Math.min(totalPages, p+1))}
                  disabled={page === totalPages}
                  className="p-2 rounded-lg border border-gray-300 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  →
                </button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

export default BookList;
